# Generated by Django 4.2.7 on 2023-12-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0003_remove_article_author_remove_article_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='detailed_description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Подробное описание'),
        ),
    ]
